name: CI
on:
  push:
    branches:
      - feature/statistics-ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.0'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Install dependencies
      run: yarn
    - name: Build static site
      run: yarn build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync build/ s3://stats-kovan.reflexer.finance --acl public-read --follow-symlinks --delete
